-- 010_partner_profiles.sql
-- Turns the private team roster into a public marketplace.
--
-- team_members was deliberately admin-only: no anon grant, photos in a private
-- bucket, and a comment in 002 saying it must stay off the public website. That
-- was correct while the roster was staff. It is now the partner roster, so the
-- profile has to be public, and the reversal has to be deliberate about what it
-- exposes.
--
-- The exposure boundary is a view, not the table. public_partners lists its
-- columns explicitly and omits phone, email, user_id, portal_status and
-- is_sample. anon is granted SELECT on the view only; team_members keeps no anon
-- policy, so a query against the table still returns nothing. If someone later
-- widens the view by hand, the base table is still closed.
--
-- Partner agreements are recorded in an append-only table with no update or
-- delete policy at all. terms_hash is computed server-side from the exact text
-- that was on screen, so the record proves what was accepted rather than what
-- the page happens to say today.
--
-- Run: supabase db query --linked -f supabase/010_partner_profiles.sql
-- Then: 010b_cities.sql (generated by scripts/build-city-seed.ts)

begin;

-- ---------------------------------------------------------------------------
-- Marketplace fields on the roster
-- ---------------------------------------------------------------------------
alter table public.team_members
  add column if not exists slug text,
  add column if not exists headline text not null default '',
  add column if not exists tagline text not null default '',
  add column if not exists years_experience int not null default 0
    check (years_experience >= 0),
  add column if not exists verified boolean not null default false,
  add column if not exists is_accepting_jobs boolean not null default true,
  -- Sample partners exist so the directory is not empty during development.
  -- They are labelled, excluded from booking, and can never collect a review.
  add column if not exists is_sample boolean not null default false;

-- Only approved, active partners get a public URL. Nullable because admin can
-- add someone before they have chosen a slug.
create unique index if not exists team_members_slug_key
  on public.team_members (slug) where slug is not null and not is_sample;

-- ---------------------------------------------------------------------------
-- Cities
--
-- DDL only; scripts/build-city-seed.ts generates 010b_cities.sql with the rows.
-- partner_areas references it so a service area can never be a free-text typo.
-- ---------------------------------------------------------------------------
create table if not exists public.cities (
  code          text primary key,
  name          text not null,
  display_name  text not null,
  province_code text not null default '',
  province_name text not null default '',
  region_code   text not null default '',
  -- Same name in different provinces, so the UI can always qualify it.
  disambiguated boolean not null default false
);

create index if not exists cities_display_name_idx on public.cities (display_name);
create index if not exists cities_province_idx on public.cities (province_name);

alter table public.cities enable row level security;
-- Reference data, not private. Readable by everyone, writable by nobody but
-- service_role.
drop policy if exists cities_public_read on public.cities;
create policy cities_public_read on public.cities
  for select to anon, authenticated using (true);
revoke all on public.cities from anon, authenticated;
grant select on public.cities to anon, authenticated;
grant select, insert, update, delete on public.cities to service_role;

-- ---------------------------------------------------------------------------
-- What a partner can do, and where they work
-- ---------------------------------------------------------------------------
create table if not exists public.partner_services (
  partner_id uuid not null references public.team_members(id) on delete cascade,
  service_id uuid not null references public.services(id) on delete cascade,
  primary key (partner_id, service_id)
);

create table if not exists public.partner_areas (
  partner_id uuid not null references public.team_members(id) on delete cascade,
  city_code   text not null references public.cities(code) on delete cascade,
  primary key (partner_id, city_code)
);

create index if not exists partner_areas_city_idx on public.partner_areas (city_code);

alter table public.partner_services enable row level security;
alter table public.partner_areas enable row level security;

-- Both are written by the registration API using the service role, after it has
-- resolved the caller. No member writes these directly, so there is no policy
-- for them.
revoke all on public.partner_services, public.partner_areas from anon, authenticated;
grant select, insert, update, delete on public.partner_services to service_role;
grant select, insert, update, delete on public.partner_areas to service_role;

-- ---------------------------------------------------------------------------
-- Agreement acceptance
--
-- Append-only. No update and no delete policy exists, so an accepted agreement
-- cannot be quietly edited or removed.
-- ---------------------------------------------------------------------------
create table if not exists public.partner_agreements (
  id           uuid primary key default gen_random_uuid(),
  partner_id   uuid not null references public.team_members(id) on delete cascade,
  version      text not null,
  terms_hash   text not null,
  name_typed   text not null,
  accepted_at  timestamptz not null default now(),
  ip           text not null default '',
  user_agent   text not null default ''
);

create index if not exists partner_agreements_partner_idx
  on public.partner_agreements (partner_id, accepted_at desc);

alter table public.partner_agreements enable row level security;

drop policy if exists partner_agreements_admin_read on public.partner_agreements;
create policy partner_agreements_admin_read on public.partner_agreements
  for select to authenticated using (public.is_admin());

-- service_role inserts. authenticated is revoked entirely, so an approval by an
-- admin cannot rewrite the acceptance record.
revoke all on public.partner_agreements from anon, authenticated;
grant select, insert on public.partner_agreements to service_role;

-- Rejecting any UPDATE or DELETE here, even from service_role, is what makes the
-- record trustworthy. A mistake is corrected by agreement with the partner, not
-- by rewriting history.
create or replace function public.forbid_agreement_mutation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'Accepted partner agreements are immutable and cannot be updated or deleted.';
end;
$$;

drop trigger if exists trg_partner_agreements_immutable on public.partner_agreements;
create trigger trg_partner_agreements_immutable
  before update or delete on public.partner_agreements
  for each row execute function public.forbid_agreement_mutation();

-- ---------------------------------------------------------------------------
-- Public profile
--
-- The column list is the security boundary. Anything not named here is private,
-- and adding a column to team_members does not expose it.
-- ---------------------------------------------------------------------------
-- Dropped first: CREATE OR REPLACE VIEW cannot insert a column into an
-- existing column list, it only replaces rows in place.
drop view if exists public.public_partners;

create view public.public_partners as
select
  m.id,
  m.slug,
  m.name,
  m.headline,
  m.tagline,
  m.bio,
  m.photo_path,
  m.years_experience,
  m.verified,
  m.is_accepting_jobs,
  -- Exposed so the interface is forced to mark a sample as one. The samples are
  -- deliberately visible: a marketplace cannot be reviewed while the directory
  -- is empty, and a SAMPLE badge plus a not-bookable state is a stronger
  -- guarantee than hiding them. The booking picker filters on this column.
  m.is_sample,
  m.sort_order,
  m.created_at,
  (select coalesce(array_agg(s.name order by s.sort_order, s.name), '{}'::text[])
     from public.partner_services ps
     join public.services s on s.id = ps.service_id
    where ps.partner_id = m.id and s.active) as specialties,
  (select coalesce(array_agg(c.display_name order by c.display_name), '{}'::text[])
     from public.partner_areas pa
     join public.cities c on c.code = pa.city_code
    where pa.partner_id = m.id) as areas,
  -- The PSGC codes behind those areas. The booking form has to match a chosen
  -- city code against a partner's coverage, and comparing display names would
  -- put the seven San Joses in the wrong province.
  (select coalesce(array_agg(pa.city_code order by pa.city_code), '{}'::text[])
     from public.partner_areas pa
    where pa.partner_id = m.id) as area_codes,
  -- The same places, always qualified with their province. A directory card can
  -- get away with the short name, but a profile cannot: seven of them are called
  -- San Jose and the customer has to know which one they are booking.
  (select coalesce(
            array_agg(
              case when c.disambiguated and c.province_name <> ''
                then c.display_name || ', ' || c.province_name
                else c.display_name
              end
              order by c.display_name, c.province_name
            ),
            '{}'::text[])
     from public.partner_areas pa
     join public.cities c on c.code = pa.city_code
    where pa.partner_id = m.id) as area_labels,
  -- Completed work only, and only where this partner was actually the one on
  -- the job. Reviews arrive in a later round, so there is no rating column yet.
  (select count(*)::int
     from public.assignments a
     join public.bookings b on b.id = a.booking_id
    where a.member_id = m.id and b.status = 'Completed') as jobs_completed
from public.team_members m
where m.active
  and m.portal_status = 'approved'
  and m.slug is not null;

grant select on public.public_partners to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Partner photos become public; writing stays gated
-- ---------------------------------------------------------------------------
update storage.buckets set public = true where id = 'team-photos';

-- public=true makes objects readable by URL. It does not grant insert or
-- delete, so the existing authenticated-only policies still apply, and the
-- migration that added them is left untouched.
drop policy if exists team_photo_insert_staff on storage.objects;
create policy team_photo_insert_staff on storage.objects
  for insert to authenticated
  with check (bucket_id = 'team-photos');

drop policy if exists team_photo_select_staff on storage.objects;
create policy team_photo_select_staff on storage.objects
  for select to authenticated
  using (bucket_id = 'team-photos');

drop policy if exists team_photo_delete_staff on storage.objects;
create policy team_photo_delete_staff on storage.objects
  for delete to authenticated
  using (bucket_id = 'team-photos');

commit;

-- Verification
do $$
declare
  v_cols     int;
  v_tables   int;
  v_fn       int;
  v_trg      int;
  v_bucket   boolean;
  v_seed     int;
begin
  select count(*) into v_cols from information_schema.columns
   where table_schema='public' and table_name='team_members'
     and column_name in ('slug','headline','tagline','years_experience',
                         'verified','is_accepting_jobs','is_sample');
  select count(*) into v_tables from pg_tables
   where schemaname='public'
     and tablename in ('cities','partner_services','partner_areas','partner_agreements');
  select count(*) into v_fn from pg_proc
   where proname in ('forbid_agreement_mutation','is_admin')
     and pronamespace='public'::regnamespace;
  select count(*) into v_trg from pg_trigger
   where tgname='trg_partner_agreements_immutable' and not tgisinternal;
  select public from storage.buckets where id='team-photos' into v_bucket;
  select count(*) into v_seed from public.cities;

  raise notice 'V-N team_members cols=% (7), tables=% (4), functions=% (2), immutability trigger=% (1), bucket public=% , cities seeded=% (expect 0 until 010b)',
    v_cols, v_tables, v_fn, v_trg, v_bucket, v_seed;
  if v_cols <> 7 or v_tables <> 4 or v_fn < 1 or v_trg <> 1 or coalesce(v_bucket,false) = false then
    raise exception 'V-N FAILED';
  end if;
end $$;
