 "use client";
import { useMemo, useState } from "react";
import Link from "next/link";

const steps=["Service","Property","Scope","Materials","Location","Schedule","Customer","Review"];
const serviceOptions=["Home Cleaning","Deep Cleaning","Move-In / Move-Out","Small Business"];
const propertyOptions=["Condo","Apartment","House","Office","Shop/Studio","Other"];
const areas=["Living room","Bedrooms","Kitchen","Bathrooms","Floors","Windows","Balcony","Appliances","Other"];

export default function Book() {
 const [step,setStep]=useState(0);
 const [submitted,setSubmitted]=useState(false);
 const [data,setData]=useState<Record<string,any>>({service:"",property:"",areas:[],condition:"Normal",materials:"Customer provides materials",time:"Morning"});
 const set=(k:string,v:any)=>setData(d=>({...d,[k]:v}));
 const toggleArea=(a:string)=>set("areas",(data.areas||[]).includes(a)?data.areas.filter((x:string)=>x!==a):[...(data.areas||[]),a]);
 const estimate=useMemo(()=>({cleaners:data.property==="House"||data.property==="Office"?2:1,hours:data.service==="Deep Cleaning"?6:5,price:data.service==="Deep Cleaning"?"₱3,500+":"₱1,300+"}),[data]);
 if(submitted) return <main><header className="header"><div className="container nav"><Link href="/" className="logo">MALTO<small>CLEANING SERVICES</small></Link></div></header><div className="booking-wrap"><div className="booking-shell"><div className="eyebrow">REQUEST RECEIVED</div><h2>Thank you.</h2><p className="lead">Your cleaning request has been received. MALTO will review the request, check availability, confirm the final price and contact you.</p><div className="notice"><strong>Request ID:</strong> MAL-20261004-1042<br/><strong>Requested appointment:</strong> {data.date || "Your requested date"} — {data.time}</div><Link className="btn" href="/">BACK TO HOME</Link></div></div></main>;
 const next=()=>setStep(s=>Math.min(7,s+1)); const back=()=>setStep(s=>Math.max(0,s-1));
 return <main><header className="header"><div className="container nav"><Link href="/" className="logo">MALTO<small>CLEANING SERVICES</small></Link><Link className="small" href="/">Back to website</Link></div></header>
 <div className="booking-wrap"><div className="booking-shell"><div className="progress">{steps.map((_,i)=><span className={i<=step?"active":""} key={i}/>)}</div><div className="eyebrow">STEP {step+1} OF 8</div><h2>{steps[step]}</h2>
 {step===0&&<div className="choice-grid">{serviceOptions.map(x=><label className="choice" key={x}><input type="radio" checked={data.service===x} onChange={()=>set("service",x)}/>{x}</label>)}</div>}
 {step===1&&<div className="form-grid"><div className="field"><label>Property Type</label><select value={data.property} onChange={e=>set("property",e.target.value)}><option value="">Select</option>{propertyOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Approximate sqm</label><input value={data.sqm||""} onChange={e=>set("sqm",e.target.value)}/></div><div className="field"><label>Bedrooms</label><input type="number" value={data.bedrooms||""} onChange={e=>set("bedrooms",e.target.value)}/></div><div className="field"><label>Bathrooms</label><input type="number" value={data.bathrooms||""} onChange={e=>set("bathrooms",e.target.value)}/></div></div>}
 {step===2&&<><div className="choice-grid">{areas.map(a=><label className="choice" key={a}><input type="checkbox" checked={(data.areas||[]).includes(a)} onChange={()=>toggleArea(a)}/>{a}</label>)}</div><div className="field" style={{marginTop:18}}><label>Condition</label><select value={data.condition} onChange={e=>set("condition",e.target.value)}>{["Light","Normal","Needs attention","Heavy buildup"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field" style={{marginTop:18}}><label>Notes</label><textarea value={data.scopeNotes||""} onChange={e=>set("scopeNotes",e.target.value)}/></div></>}
 {step===3&&<div className="choice-grid">{["Customer provides materials","MALTO provides materials"].map(x=><label className="choice" key={x}><input type="radio" checked={data.materials===x} onChange={()=>set("materials",x)}/>{x}</label>)}</div>}
 {step===4&&<div className="form-grid"><div className="field full"><label>Address</label><input value={data.address||""} onChange={e=>set("address",e.target.value)}/></div><div className="field"><label>City / Municipality</label><input value={data.city||""} onChange={e=>set("city",e.target.value)}/></div><div className="field"><label>Province</label><input value={data.province||""} onChange={e=>set("province",e.target.value)}/></div><div className="field"><label>Landmark</label><input value={data.landmark||""} onChange={e=>set("landmark",e.target.value)}/></div><div className="field"><label>Access instructions</label><input value={data.access||""} onChange={e=>set("access",e.target.value)}/></div></div>}
 {step===5&&<div className="form-grid"><div className="field"><label>Preferred Date</label><input type="date" value={data.date||""} onChange={e=>set("date",e.target.value)}/></div><div className="field"><label>Preferred Time</label><select value={data.time} onChange={e=>set("time",e.target.value)}><option>Morning</option><option>Afternoon</option><option>Evening</option></select></div><div className="field full"><div className="notice">Subject to availability.</div></div></div>}
 {step===6&&<div className="form-grid"><div className="field"><label>Full Name</label><input value={data.name||""} onChange={e=>set("name",e.target.value)}/></div><div className="field"><label>Mobile Number</label><input value={data.mobile||""} onChange={e=>set("mobile",e.target.value)}/></div><div className="field full"><label>Email</label><input type="email" value={data.email||""} onChange={e=>set("email",e.target.value)}/></div><div className="field full"><label>Notes</label><textarea value={data.notes||""} onChange={e=>set("notes",e.target.value)}/></div><div className="field full"><label>Optional Photo Upload</label><input type="file" accept="image/*" /></div></div>}
 {step===7&&<><div className="notice">Final price is confirmed after MALTO reviews the request.</div><div className="estimate"><p><strong>Service:</strong> {data.service||"—"}</p><p><strong>Estimated cleaners:</strong> {estimate.cleaners}</p><p><strong>Estimated hours:</strong> {estimate.hours}</p><p><strong>Estimated price range:</strong> {estimate.price}</p></div></>}
 <div className="booking-actions">{step>0?<button className="btn secondary" onClick={back}>BACK</button>:<span/>}{step<7?<button className="btn" onClick={next}>CONTINUE</button>:<button className="btn" onClick={()=>setSubmitted(true)}>REQUEST BOOKING</button>}</div>
 </div></div></main>
}